project:
  type: website
  output-dir: docs
  render:
    - index.qmd
    - achievements.qmd
    - code.qmd
    - collaborations.qmd
    - events_upcoming.qmd
    - events_past.qmd
    - trainings.qmd
    - history.qmd
    - organization.qmd
    - publications.qmd
    - resources.qmd
    - scope.qmd
    - status.qmd
    - subteams.qmd

website:
  title: "EFSPI/EFPIA EIWG"
  navbar:
    background: "#2C3791"
    left:
    - text: "About"
      menu:
        - text: "About"
          href: index.html
        - text: "History"
          href: history.html
        - text: "Scope"
          href: scope.html
        - text: "Status"
          href: status.html
        - text: "Organization"
          href: organization.html
        - text: "Collaborations"
          href: collaborations.html
        - text: "Achievements per year"
          href: achievements.html
    - text: "Subteams"
      href: subteams.html
    - text: "Trainings"
      href: trainings.html
    - text: "Publications"
      href: publications.html
    - text: "Code"
      href: code.html
    - text: "Events"
      menu:
        - text: "Upcoming events"
          href: events_upcoming.html
        - text: "Past events"
          href: events_past.html
    - text: "Further resources"
      href: resources.html

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: source

