---
title: "Oncology estimand working group: achievements per year"
date: last-modified
output: 
  rmarkdown::html_document:
    highlight: pygments
    number_sections: yes
    self_contained: yes
    toc: yes
    toc_depth: 3
    toc_float: yes
---

## Achievements 2023

### Non-inferiority sub-team

- PSI 2023 presentation
- Preparation of paper on estimands in non-inferiority trials
- Preparation of PSI 2024 proposal including a panel of regulators

### Training sub-team

- Organized the webinar "Proposing Estimands from Different Perspectives", which showed a case study in heart failure presented by the perspective of multiple stakeholders (patient, clinician, regulator, health technology assessor and statistician). The webinar had a record of more than 800 people registered to attend. (March 2023)

### Communications sub-team
- Participated in APBG Estimands Webinar
- Preparation of PSI 2024 proposal on estimand thinking and statistical leadership

### Estimation sub-team
- Preparation of manuscript on treatment policy estimation

### Reporting sub-team
- Agreed to collaborate with NIH on trial disclosure and estimands
- Invited presentation at JSM 2023 by Melanie Wright “Realizing the benefits of estimands to increase transparency in the reporting and communication of trial results”
- Preparation of manuscript on the reporting of estimands and intercurrent events in clinical study reports

### Intercurrent Events sub-team
- Newly formed to tackle uncertainty around the meaning of different intercurrent event strategies, which is a major barrier to effective implementation of the estimands framework 
- Identified several key areas of uncertainty to target in 2024

### Estimands in Early Phase [I/II] & Clinical Pharmacology Studies sub-team
- Submitted and received referee comments on paper “Tutorial on How Estimands can be Applied to Bioequivalence and Related Clinical Pharmacology Trials”. (Hope for open access in 2024). 
- Presented to PSI conference (linked to above bioequivalence topic) “Does it Make Sense to Apply the Estimand Framework to Clinical Pharmacology Trials”. June 2023
- Reviewed and submitted comments for FDA draft guidance : Statistical Approaches to Establishing Bioequivalence (December 2022) 
- Knowledge sharing and discussion on a number of topics. 

### HTA and RWE sub-team
- Antonia Morga and Pepa Polavieja presented on behalf of the group on “The ICH E9(R1) Addendum in the context of Health Technology Assessments: methodological considerations and recommendations” at an Estimand session during the PSI conference in London (June 2023)
- The group presented a poster at ISPOR Europe (November 2023) titled: “Estimands in Health Technology Assessments: methodological considerations and recommendations”


## Achievements 2022

### Training sub-team

The training committee has continued to work on webinars for their training series ‘EIWG Estimand Training Academy’ targeting anyone working in clinical trials.

All trainings provided so far are freely available as ‘Video-on-Demand’
[PSI Portal](https://psiweb.org/vod/Index/) or YouTube on the EFPIA channel

### Estimation sub-team

Estimating the treatment-policy strategy with continuous data and incomplete post-IE follow-up is a relevant and under-researched issue. To address it, the group has assessed the performance of different estimators – based on either multiple imputation (MI) or mixed effect models (MMRM) – for simulated trials based on the HbA1c endpoint from the PIONEER1 study. The properties of the estimators (bias and variance shown here) generally confirm the equivalence of MI and MMRM approaches (if the same assumptions are made) and the particular importance of collecting post-IE data. The complex trade-off between variance inflation and accuracy needs to be carefully evaluated further.

### Early Phase & Other Studies sub-team

This sub-team was created as a forum for both statisticians (industry & academia) and pharmacokinetics as well as regulators to help bridge the gap in the estimands framework with regards other study types including early phase and clinical pharmacology where the purpose is not confirmatory efficacy.
We presented a poster (Does the Estimand Framework Add Value to Clinical Pharmacology Trials?) at the PSI conference 2022. A manuscript is under preparation with focus on bioequivalence/bioavailability studies and is planned to be published in a clinical pharmacology journal in 2023.
The implementation of estimands in early phase studies (including dose finding and CRMs) are also being discussed within this workstream. We aim to share some of our work at the PSI conference in 2023.

### Communications sub-team

In 2022 the homepage of the group was fully revised and summarizes all work of the EIWG.
Posters of the working group were presented at the 2022 PSI conference in Gothenburg and the 2022 Regulatory Industry workshop in Basel.

### Estimands in non-inferiority trials sub-team
The ICH E9(R1) includes limited guidance in relation to non-inferiority (NI) trials. Current regulatory guidelines on NI trials predate the release of the addendum and the per protocol analysis set plays an important part in the EMA NI guidelines. In contrast, ICH E9(R1) questions the role of the per protocol set and this has led to confusion as regards to the applicability of the EMA Points to consider on switching between superiority and non-inferiority.
The sub-team is discussing which estimands can be considered relevant in an NI setting and how they fit into existing guidelines. The sub-team members are sharing recent regulatory feedback on NI trials, and we are discussing questions such as
- What is the underlying clinical question to be answered in an NI trial?
- Are two estimands with different strategies for intercurrent events required to reflect the spirit in the EMA Points to consider on switching between superiority and non-inferiority?
- Can protocol violations be handled as intercurrent events? Is there any remaining role for a Per Protocol analysis set?
- Can different estimands be used to show NI and superiority in the same trial (hierarchical set-up)?
- How does the estimand framework impact the choice of the NI margin?





