---
title: "Collaborations"
date: last-modified
execute:   
  freeze: auto  # re-render only when source changes
output: 
  rmarkdown::html_document:
    highlight: pygments
    number_sections: yes
    self_contained: yes
    toc: yes
    toc_depth: 3
    toc_float: yes
---

## European special interest group “Estimands in oncology”, sponsored by PSI and EFSPI and ASA scientific working group of the ASA biopharmaceutical section

- **Mission:** The cross-industry working group ([oncoestimand.org](http://www.oncoestimand.org)) was initiated to foster a common understanding and consistent implementation of the estimand framework in oncology clinical trials.
- **Liaison:** Stefan Englert

## PhUSE 
- **Mission:** Sharing ideas, tools and standards around data, statistical and reporting technologies to advance the future of life sciences.
- **Liaison:** Armin Schueler

## TransCelerate
- **Mission:** TransCelerate BioPharma’s mission is to collaborate across the global biopharmaceutical research and development community to identify, prioritize, design, and facilitate the implementation of solutions designed to drive the efficient, effective and high-quality delivery of new medicines.
- **Liaison:** Pepa Polavieja and Helle Lynggaard



