---
title: "Organization"
date: last-modified
output: 
  rmarkdown::html_document:
    highlight: pygments
    number_sections: yes
    self_contained: yes
    toc: yes
    toc_depth: 3
    toc_float: yes
---

## Leads

Chrissie Fletcher from [GSK](http://www.gsk.com), Amel Besseghir from [Fresenius Kabi](https://www.fresenius-kabi.com) and Nanco Hefting from [Lundbeck](https://www.lundbeck.com)

## Communication Lead

Stefan Englert from [J&J](https://www.jnj.com/).

## Task forces and members

The working group operates within eight sub-teams. Objectives and member rosters of these sub-teams are available [here](subteams.html).

## Activities

Beyond work in the subteams, the aim of the working group is to provide answers to estimand implementation questions through a variety of activities. These will include: 

 + Collaborating with experts to refine and possibly extend implementation.
 + Publishing reviews, case studies, and white papers with recommendations, for statisticians and non-statisticians.
 + Interacting with clinicians, regulators and the broader clinical community to obtain a better understanding of their requirements. 
 + Providing trainings, workshops and talks.