---
title: "Status"
date: last-modified
output: 
  rmarkdown::html_document:
    highlight: pygments
    number_sections: yes
    self_contained: yes
---

```{r setup, include=FALSE}
## load packages
packs.html <- c("knitr", "pander", "reporttools", "dplyr", "readxl")
for (i in 1:length(packs.html)){library(packs.html[i], character.only = TRUE)}

knitr::opts_chunk$set(echo = TRUE)
panderOptions('table.alignment.default', function(df){ifelse(sapply(df, is.numeric), 'right', 'left')})

path <- getwd()

## =================================================================
## functions
## =================================================================
source(file = paste(path, "/tools/mydisp.r", sep = ""))
source(file = paste(path, "/tools/lead.r", sep = ""))

## =================================================================
## member list
## =================================================================
email <- as.data.frame(read_excel(paste(path, "/data/members.xlsx", sep = ""), col_types = NULL))

## function to display
ind <- email %>% filter(Type == "Full") 
loc <- ind$Name
com <- ind$Company

## Current month
today <- Sys.Date()
tod <- format(today, format = "%d %B %Y")
```

As of `r tod`, the working group

-   has `r length(loc)` members representing `r length(unique(com))` companies / institutions,
-   regularly organizes sessions and presents at conferences,
-   has started to interact with partner organizations.

## Current Members

```{r, echo = FALSE, results = 'asis', message = FALSE}
t1 <- (email %>% filter(Type == "Full") %>% arrange(Company) %>% select(Name, Company, Function))
rownames(t1) <- NULL
kable(t1) 
```

## Past Members

```{r, echo = FALSE, results = 'asis', message = FALSE}
t1 <- (email %>% filter(Type == "Retired") %>% arrange(Company) %>% select(Name, Company, Function))
rownames(t1) <- NULL
kable(t1) 
```
