---
title: "Sub-teams"
date: "`r Sys.Date()`"
output: 
  rmarkdown::html_document:
    highlight: pygments
    number_sections: yes
    self_contained: yes
    toc: yes
    toc_depth: 3
    toc_float: yes
---

The working group operates within regional and topic sub-teams. Objectives and member rosters of these sub-teams are available below.

```{r setup, include=FALSE}
## load packages
packs.html <- c("knitr", "pander", "reporttools", "dplyr", "readxl")
for (i in 1:length(packs.html)){library(packs.html[i], character.only = TRUE)}

knitr::opts_chunk$set(echo = TRUE)
panderOptions('table.alignment.default', function(df){ifelse(sapply(df, is.numeric), 'right', 'left')})

path <- getwd()

## =================================================================
## functions
## =================================================================
source(file = paste(path, "/tools/mydisp.r", sep = ""))
source(file = paste(path, "/tools/lead.r", sep = ""))
source(file = paste(path, "/tools/obj.r", sep = ""))

## =================================================================
## member list
## =================================================================
email <- as.data.frame(read_excel(paste(path, "/data/members.xlsx", sep = ""), col_types = NULL))
objectives <- as.data.frame(read_excel(paste(path, "/data/objectives.xlsx", sep = ""), col_types = NULL))

## Current month
today <- Sys.Date()
tod <- format(today, format = "%d %B %Y")

## Subteams
subteams <- c("Communications", "LateStage", "Reporting", "Estimation", "NonInferiority", "Training", "IntercurrentEvent", "EarlyPhase", "NorthAmerica", "StudyDesign", "China")
subteams_names <- c("Communications", "RWE and HTA", "Reporting", "Estimation", "Non-inferiority", "Training", "Intercurrent event", "Estimands in Early Phase [I/II] & Clinical Pharmacology Studies", "North America", "Study Design", "China")
```

# Regional Subteams

```{r, label = "regional", echo = FALSE, message = FALSE, warning = FALSE, results = "asis"}
# how to do this with child documents: https://gist.github.com/rmoff/a043676a2f084b81a434
out2 <- NULL
for (i in c(9,11)){
  out2 <- c(out2, knit_expand('tools/subteam.Rmd'))
}

# the "knit" command somehow produces unwanted output, this is why I assign its output to a and use a separate chunk to display a
cat(knit(text = unlist(paste(out2, collapse = '\n')), quiet = TRUE))
```

# Topic Subteams

```{r, label = "topic", echo = FALSE, message = FALSE, warning = FALSE, results = "asis"}
# how to do this with child documents: https://gist.github.com/rmoff/a043676a2f084b81a434
out2 <- NULL
for (i in c(1:8,10)){
  out2 <- c(out2, knit_expand('tools/subteam.Rmd'))
}

# the "knit" command somehow produces unwanted output, this is why I assign its output to a and use a separate chunk to display a
cat(knit(text = unlist(paste(out2, collapse = '\n')), quiet = TRUE))
```


